Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# a)
addition = arr + 2

# b)
multiplication = arr * 3

# c)
division = arr / 2

print("Original Array:", arr)
print("After Addition:", addition)
print("After Multiplication:", multiplication)
print("After Division:", division)


Original Array: [1 2 3 4 5]
After Addition: [3 4 5 6 7]
After Multiplication: [ 3  6  9 12 15]
After Division: [0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])


In [2]:
# a)
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed Array:", reversed_arr)

# b)
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

def most_frequent(arr):
    unique, counts = np.unique(arr, return_counts=True)
    max_freq = unique[np.argmax(counts)]
    indices = np.where(arr == max_freq)[0]
    return max_freq, indices

freq_x, indices_x = most_frequent(x)
freq_y, indices_y = most_frequent(y)

print(f"Most frequent value in x: {freq_x}, Indices: {indices_x}")
print(f"Most frequent value in y: {freq_y}, Indices: {indices_y}")


Reversed Array: [5 4 6 3 2 1]
Most frequent value in x: 1, Indices: [0 5 7 8 9]
Most frequent value in y: 1, Indices: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column


In [4]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# a)
value1 = arr[0, 1]

# b)
value2 = arr[2, 0]

print("Element at (1st row, 2nd column):", value1)
print("Element at (3rd row, 1st column):", value2)


Element at (1st row, 2nd column): 20
Element at (3rd row, 1st column): 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?


In [3]:
my_name = np.linspace(10, 100, 25)

print("Array:", my_name)
print("Dimensions:", my_name.ndim)
print("Shape:", my_name.shape)
print("Total Elements:", my_name.size)
print("Data Type:", my_name.dtype)
print("Bytes Consumed:", my_name.nbytes)

transposed_array = my_name.reshape(25, 1)
print("Transposed Array (using reshape()):\n", transposed_array)

transposed_t = my_name.T
print("Transposed using .T:", transposed_t)


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Bytes Consumed: 200
Transposed Array (using reshape()):
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transposed using .T: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [8]:
ucs420_swastika = np.array([[10,20,30,40],
                       [50,60,70,80],
                       [90,15,20,35]])
print("The array:",ucs420_swastika)

mean_value = np.mean(ucs420_swastika)
median_value = np.median(ucs420_swastika)
max_value = np.max(ucs420_swastika)
min_value = np.min(ucs420_swastika)
unique_elements = np.unique(ucs420_swastika)

print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_elements)

reshaped_ucs420_swastika = ucs420_swastika.reshape(4, 3)
print("\nReshaped_ucs420_swastika:\n", reshaped_ucs420_swastika)

resized_ucs420_swastika = np.resize(ucs420_swastika, (2, 3))
print("\nResized_ucs420_swastika:\n", resized_ucs420_swastika)

The array: [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped_ucs420_swastika:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized_ucs420_swastika:
 [[10 20 30]
 [40 50 60]]
